### ISSUE TITLE
Pyfreenect2 cannot find -lfreenect2

### ISSUE THREAD

**Issue by omidkk** [remexre/pyfreenect2#15]
Hi,
I am trying to install pyfreenect2 on ubuntu 14.04, but it gives this error:

```
/usr/bin/ld: cannot find -lfreenect2
collect2: error: ld returned 1 exit status
error: command 'c++' failed with exit status 1
```

I have used this link [https://github.com/OpenKinect/libfreenect2/blob/master/README.md#linux](url) to install freenect.

Thanks

**Comment by omidkk** [comment]
I have solved this problem, but still I can not run test.py it gives this error:
`ImportError: libfreenect2.so.0.2: cannot open shared object file: No such file or directory
`

**Comment by c-maxey** [comment]
Try setting your LD_LIBRARY_PATH to include the freenect2 library via:

export LD_LIBRARY_PATH=$HOME/freenect2/lib:$LD_LIBRARY_PATH

**Comment by negvet** [comment]
How did you solve 
`/usr/bin/ld: cannot find -lfreenect2`
problem?

**Comment by pedrombmachado** [comment]
Hi @Negvet ,
  I had the same issue and it worked for me. I added the export to .bashrc and it is now working.

**Comment by omidkk** [comment]
Try setting your LD_LIBRARY_PATH to include the freenect2 library via:

export LD_LIBRARY_PATH=$HOME/freenect2/lib:$LD_LIBRARY_PATH
